# -*- coding: utf-8 -*-

"""
Main module.

This module contains functions that get LLM's anomaly detection results.
"""
from anomalies import get_anomaly_list_within_seq, str2idx
from data import sig2str


def get_anomalies(
            seq, 
            msg_func, 
            model_func, 
            sep=',', 
            space=False, 
            decimal=0, 
            rescale=True,
            num_iters=1, 
            alpha=0.5, 
#            gpt_model = "gpt-3.5-turbo", 
#             frequency_penalty = 0, 
#             logit_bias = None,           
#             logprobs = False, 
#             top_logprobs = None, 
#             max_tokens = None, 
#             n = 1,       
#             presence_penalty = 0, 
#             response_format = {"type": "text"},
#             seed = None, 
#             stop = None, 
#             stream = False, 
#             temperature = 1,
#             top_p = 1, 
#             tools = [], 
#             tool_choice = 'none', 
#             user = ""
            ):
    """Get LLM anomaly detection results.

    The function get the LLM's anomaly detection and converts them into an 1D array

    Args:
        seq (ndarray):
            The sequence to detect anomalies.
        msg_func (func):
            Function to create message prompt.
        model_func (func):
            Function to get LLM answer.
        num_iters (int):
            Number of times to run the same query.
        sep (str):
            String to separate each element in values. Default to `","`.
        space (bool):
            Whether to add space between each digit in the result. Default to `False`.
        decimal (int):
            Number of decimal points to keep from the float representation. Default to `0`.
        rescale(bool):
            Whether to rescale the time series. Default to `True`
        alpha (float):
            Percentage of total number of votes that an index needs to have to be
            considered anomalous. Default: 0.5
        decimal (int):
            Number of decimal points to keep from the float representation. Default to `0`.
        gpt_model (str): 
            GPT model name. Defaults to `"gpt-3.5-turbo"`.
        frequency_penalty (number or null): 
            Number between -2.0 and 2.0. Positive values penalize new tokens based on their 
            existing frequency in the text so far, decreasing the model's likelihood to repeat 
            the same line verbatim. Defaults to `0`.
        logit_bias (map):
            Modify the likelihood of specified tokens appearing in the completion.
            Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) 
            to an associated bias value from -100 to 100. Mathematically, the bias is added to the 
            logits generated by the model prior to sampling. The exact effect will vary per model, 
            but values between -1 and 1 should decrease or increase likelihood of selection; 
            values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
            Defaults to `None`.
        logprobs (bool or null): 
            Whether to return log probabilities of the output tokens or not. If true, returns the 
            log probabilities of each output token returned in the content of message. This option 
            is currently not available on the gpt-4-vision-preview model. Defaults to `False`.
        top_logprobs (int or null): 
            An integer between 0 and 20 specifying the number of most likely tokens to return at 
            each token position, each with an associated log probability. logprobs must be set to 
            `True` if this parameter is used. Default to `None`.
        max_tokens (int or null): 
            The maximum number of tokens that can be generated in the chat completion. Defaults to `None`.
        n (int or null):
            How many chat completion choices to generate for each input message. Note that you will be charged 
            based on the number of generated tokens across all of the choices. Defaults to `1`.
        present_penalty (number or null): 
            Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the 
            text so far, increasing the model's likelihood to talk about new topics. Defaults to `0`.
        response_format (object):
            An object specifying the format that the model must output. Compatible with GPT-4 Turbo 
            and all GPT-3.5 Turbo models newer than gpt-3.5-turbo-1106. 
            Setting to { "type": "json_object" } enables JSON mode, which guarantees the message 
            the model generates is valid JSON.
            Defaults to `{"type": "text"}`
        seed (int or null):
            This feature is in Beta. If specified, our system will make a best effort to sample deterministically, 
            such that repeated requests with the same seed and parameters should return the same result. 
            Determinism is not guaranteed, and you should refer to the system_fingerprint response parameter 
            to monitor changes in the backend. Defaults to `None`.
        stop (str/array/null): 
            Up to 4 sequences where the API will stop generating further tokens. Defaults to `None`.
        stream (bool or null): 
            If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only 
            server-sent events as they become available, with the stream terminated by a data: [DONE] message.
            Defaults to `False`.
        temperature (number or null): 
            What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the 
            output more random, while lower values like 0.2 will make it more focused and deterministic.
            We generally recommend altering this or top_p but not both. Defaults to `1`.
        top_p (number or null): 
            An alternative to sampling with temperature, called nucleus sampling, where the model considers 
            the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising 
            the top 10% probability mass are considered.
            We generally recommend altering this or temperature but not both. Defaults to `1`.
        tools (array): 
            A list of tools the model may call. Currently, only functions are supported as a tool. 
            Use this to provide a list of functions the model may generate JSON inputs for. 
            A max of 128 functions are supported. Defaults to `[]`.
        tool_choice (str or object): 
            Controls which (if any) function is called by the model.
            `none` means the model will not call a function and instead generates a message. 
            `auto` means the model can pick between generating a message or calling a function. 
            Specifying a particular function via {"type": "function", "function": {"name": "my_function"}} 
            forces the model to call that function.
            Defaults to `none`.
        user (str): 
            A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.

    Returns:
        ndarray:
            1D array containing anomalous indices of the sequence.
    """
    message = msg_func(sig2str(seq, sep = sep, space=space, decimal = decimal, rescale = rescale))
    res_list = []
    for i in range(num_iters):
        res = model_func(message)
        ano_ind = str2idx(res, len(seq))
        res_list.append(ano_ind)
    return get_anomaly_list_within_seq(res_list, alpha=alpha)
